import { defineConfig } from 'drizzle-kit'
import fs from 'node:fs'
import path from 'node:path'

// Automatically find the correct local D1 SQLite file generated by Wrangler
function getLocalD1DbPath(): string {
  const d1BaseDir = '.wrangler/state/v3/d1/miniflare-D1DatabaseObject'
  try {
    if (fs.existsSync(d1BaseDir)) {
      const files = fs.readdirSync(d1BaseDir)
      // The actual D1 database file is named with a 64-character SHA-256 hash.
      // We filter out metadata files and select the hash file.
      const dbFile = files.find(
        (file) =>
          file.endsWith('.sqlite') &&
          !file.startsWith('metadata') &&
          file.length > 40
      )
      if (dbFile) {
        console.log(dbFile, '<============= dbFile load in local ==========>')
        return path.join(d1BaseDir, dbFile)
      }
    }
  } catch (err) {
    console.warn(
      '⚠️ [Drizzle Config] Failed to automatically resolve local D1 SQLite path:',
      err
    )
  }
  // Fallback to the known hash if dynamic resolution fails
  return path.join(
    d1BaseDir,
    'ae917dad9a27c2843d2d49e735e212070c1debd58679973a4aefaee8413c87d8.sqlite'
  )
}

export default defineConfig({
  dialect: 'sqlite',
  schema: './src/db/schema.ts',
  out: './drizzle',
  dbCredentials: {
    url: getLocalD1DbPath(),
  },
})
