/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WorkspaceSplatRouteImport } from './routes/_workspace/$'
import { Route as WorkspaceWorkspaceIndexRouteImport } from './routes/_workspace/workspace.index'
import { Route as WorkspaceWorkspaceFavoritesRouteImport } from './routes/_workspace/workspace.favorites'
import { Route as WorkspaceWorkspaceMusicRouteImport } from './routes/_workspace/workspace.music'
import { Route as WorkspaceWorkspaceTagsRouteImport } from './routes/_workspace/workspace.tags'
import { Route as WorkspaceWorkspaceTrashRouteImport } from './routes/_workspace/workspace.trash'
import { Route as WorkspaceWorkspaceWorkspacesRouteImport } from './routes/_workspace/workspace.workspaces'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as WorkspaceWorkspaceFolderIndexRouteImport } from './routes/_workspace/workspace.folder.index'
import { Route as WorkspaceWorkspaceFolderFolderIdRouteImport } from './routes/_workspace/workspace.folder.$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSplatRoute = WorkspaceSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkspaceIndexRoute = WorkspaceWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkspaceFavoritesRoute =
  WorkspaceWorkspaceFavoritesRouteImport.update({
    id: '/workspace/favorites',
    path: '/workspace/favorites',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceWorkspaceMusicRoute = WorkspaceWorkspaceMusicRouteImport.update({
  id: '/workspace/music',
  path: '/workspace/music',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkspaceTagsRoute = WorkspaceWorkspaceTagsRouteImport.update({
  id: '/workspace/tags',
  path: '/workspace/tags',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkspaceTrashRoute = WorkspaceWorkspaceTrashRouteImport.update({
  id: '/workspace/trash',
  path: '/workspace/trash',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceWorkspaceWorkspacesRoute =
  WorkspaceWorkspaceWorkspacesRouteImport.update({
    id: '/workspace/workspaces',
    path: '/workspace/workspaces',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceFolderIndexRoute =
  WorkspaceWorkspaceFolderIndexRouteImport.update({
    id: '/workspace/folder/',
    path: '/workspace/folder/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceWorkspaceFolderFolderIdRoute =
  WorkspaceWorkspaceFolderFolderIdRouteImport.update({
    id: '/workspace/folder/$folderId',
    path: '/workspace/folder/$folderId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$': typeof WorkspaceSplatRoute
  '/workspace/favorites': typeof WorkspaceWorkspaceFavoritesRoute
  '/workspace/music': typeof WorkspaceWorkspaceMusicRoute
  '/workspace/tags': typeof WorkspaceWorkspaceTagsRoute
  '/workspace/trash': typeof WorkspaceWorkspaceTrashRoute
  '/workspace/workspaces': typeof WorkspaceWorkspaceWorkspacesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/workspace/': typeof WorkspaceWorkspaceIndexRoute
  '/workspace/folder/$folderId': typeof WorkspaceWorkspaceFolderFolderIdRoute
  '/workspace/folder/': typeof WorkspaceWorkspaceFolderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$': typeof WorkspaceSplatRoute
  '/workspace/favorites': typeof WorkspaceWorkspaceFavoritesRoute
  '/workspace/music': typeof WorkspaceWorkspaceMusicRoute
  '/workspace/tags': typeof WorkspaceWorkspaceTagsRoute
  '/workspace/trash': typeof WorkspaceWorkspaceTrashRoute
  '/workspace/workspaces': typeof WorkspaceWorkspaceWorkspacesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/workspace': typeof WorkspaceWorkspaceIndexRoute
  '/workspace/folder/$folderId': typeof WorkspaceWorkspaceFolderFolderIdRoute
  '/workspace/folder': typeof WorkspaceWorkspaceFolderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/admin': typeof AdminRoute
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_workspace/$': typeof WorkspaceSplatRoute
  '/_workspace/workspace/favorites': typeof WorkspaceWorkspaceFavoritesRoute
  '/_workspace/workspace/music': typeof WorkspaceWorkspaceMusicRoute
  '/_workspace/workspace/tags': typeof WorkspaceWorkspaceTagsRoute
  '/_workspace/workspace/trash': typeof WorkspaceWorkspaceTrashRoute
  '/_workspace/workspace/workspaces': typeof WorkspaceWorkspaceWorkspacesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/_workspace/workspace/': typeof WorkspaceWorkspaceIndexRoute
  '/_workspace/workspace/folder/$folderId': typeof WorkspaceWorkspaceFolderFolderIdRoute
  '/_workspace/workspace/folder/': typeof WorkspaceWorkspaceFolderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/$'
    | '/workspace/favorites'
    | '/workspace/music'
    | '/workspace/tags'
    | '/workspace/trash'
    | '/workspace/workspaces'
    | '/api/auth/$'
    | '/api/media/$'
    | '/workspace/'
    | '/workspace/folder/$folderId'
    | '/workspace/folder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/$'
    | '/workspace/favorites'
    | '/workspace/music'
    | '/workspace/tags'
    | '/workspace/trash'
    | '/workspace/workspaces'
    | '/api/auth/$'
    | '/api/media/$'
    | '/workspace'
    | '/workspace/folder/$folderId'
    | '/workspace/folder'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/admin'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/_workspace/$'
    | '/_workspace/workspace/favorites'
    | '/_workspace/workspace/music'
    | '/_workspace/workspace/tags'
    | '/_workspace/workspace/trash'
    | '/_workspace/workspace/workspaces'
    | '/api/auth/$'
    | '/api/media/$'
    | '/_workspace/workspace/'
    | '/_workspace/workspace/folder/$folderId'
    | '/_workspace/workspace/folder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AdminRoute: typeof AdminRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/$': {
      id: '/_workspace/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof WorkspaceSplatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/': {
      id: '/_workspace/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceWorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/favorites': {
      id: '/_workspace/workspace/favorites'
      path: '/workspace/favorites'
      fullPath: '/workspace/favorites'
      preLoaderRoute: typeof WorkspaceWorkspaceFavoritesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/music': {
      id: '/_workspace/workspace/music'
      path: '/workspace/music'
      fullPath: '/workspace/music'
      preLoaderRoute: typeof WorkspaceWorkspaceMusicRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/tags': {
      id: '/_workspace/workspace/tags'
      path: '/workspace/tags'
      fullPath: '/workspace/tags'
      preLoaderRoute: typeof WorkspaceWorkspaceTagsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/trash': {
      id: '/_workspace/workspace/trash'
      path: '/workspace/trash'
      fullPath: '/workspace/trash'
      preLoaderRoute: typeof WorkspaceWorkspaceTrashRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/workspaces': {
      id: '/_workspace/workspace/workspaces'
      path: '/workspace/workspaces'
      fullPath: '/workspace/workspaces'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspacesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/workspace/folder/': {
      id: '/_workspace/workspace/folder/'
      path: '/workspace/folder'
      fullPath: '/workspace/folder/'
      preLoaderRoute: typeof WorkspaceWorkspaceFolderIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/folder/$folderId': {
      id: '/_workspace/workspace/folder/$folderId'
      path: '/workspace/folder/$folderId'
      fullPath: '/workspace/folder/$folderId'
      preLoaderRoute: typeof WorkspaceWorkspaceFolderFolderIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceSplatRoute: typeof WorkspaceSplatRoute
  WorkspaceWorkspaceFavoritesRoute: typeof WorkspaceWorkspaceFavoritesRoute
  WorkspaceWorkspaceMusicRoute: typeof WorkspaceWorkspaceMusicRoute
  WorkspaceWorkspaceTagsRoute: typeof WorkspaceWorkspaceTagsRoute
  WorkspaceWorkspaceTrashRoute: typeof WorkspaceWorkspaceTrashRoute
  WorkspaceWorkspaceWorkspacesRoute: typeof WorkspaceWorkspaceWorkspacesRoute
  WorkspaceWorkspaceIndexRoute: typeof WorkspaceWorkspaceIndexRoute
  WorkspaceWorkspaceFolderFolderIdRoute: typeof WorkspaceWorkspaceFolderFolderIdRoute
  WorkspaceWorkspaceFolderIndexRoute: typeof WorkspaceWorkspaceFolderIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSplatRoute: WorkspaceSplatRoute,
  WorkspaceWorkspaceFavoritesRoute: WorkspaceWorkspaceFavoritesRoute,
  WorkspaceWorkspaceMusicRoute: WorkspaceWorkspaceMusicRoute,
  WorkspaceWorkspaceTagsRoute: WorkspaceWorkspaceTagsRoute,
  WorkspaceWorkspaceTrashRoute: WorkspaceWorkspaceTrashRoute,
  WorkspaceWorkspaceWorkspacesRoute: WorkspaceWorkspaceWorkspacesRoute,
  WorkspaceWorkspaceIndexRoute: WorkspaceWorkspaceIndexRoute,
  WorkspaceWorkspaceFolderFolderIdRoute: WorkspaceWorkspaceFolderFolderIdRoute,
  WorkspaceWorkspaceFolderIndexRoute: WorkspaceWorkspaceFolderIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AdminRoute: AdminRoute,
  DesignSystemRoute: DesignSystemRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
